#!/usr/bin/env php
<?php

require __DIR__ . '/../../autoload.php';

use MiToTeam\MtHowMany;
use MiToTeam\MtHowManyCommand;
use Symfony\Component\Console\Application;

$application = new Application(MtHowMany::APP_NAME, MtHowMany::APP_VERSION);
$command = new MtHowManyCommand();

$application->add($command);
$application->setDefaultCommand($command->getName());

$application->run();
